### ISSUE TITLE
Trouver un $^%! de nom à ce package

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/savoirfR#10]
Des idées ?

- teachr ?
- professr ?
- tutr ?
- entrainr ?

**Comment by MaelTheuliere** [comment]
poke @jengelaere @MurielleL @TerseurBr @MZellou

**Comment by MurielleDelmotte** [comment]
pratiquR ?
appliquR?

**Comment by TerseurBr** [comment]
repetitR ?
preceptR ?

arpentR ?  (avec une arriere pensée espace naturel, amenagement, etc... en plus du coté je cherche et j'expérimente)

trituratR ?

....rabachR (!)
comptepourdubeuR ?
sparringpartneR ?


(sinon, tutR, c'est pas mal)

**Comment by jengelaere** [comment]
exRcices
complementR
savoir_fR
modulR
parfR
persevR
solitR
sprintR
stagiR

**Comment by MurielleDelmotte** [comment]
@jengelaere J'aime bien exRcices et savoir_fR!

**Comment by MaelTheuliere** [comment]
Pour info j'ai utilisé github action pour mettre en place une chaine d'intégration qui produit un site pkgdown. Cela permet d'avoir les exos aussi en vignette : https://mtes-mct.github.io/parcours_r_exercices/
Est ce que vous trouvez ça utile ?
C'est en tout cas simplissime de faire ça avec usthis : 
`usethis::use_pkgdown()
usethis::use_github_action("pkgdown")
`

**Comment by MurielleDelmotte** [comment]
C'est top, et ce sera de toute manière utile en formation, lorsque nous aurons enlevé les exo des supports actuels !

**Comment by MaelTheuliere** [comment]
Bon ben c'est validé, j'ai mis un coup de polish sur le site, ça commence à rendre propre, reste plus qu'à remplir tout ça : https://mtes-mct.github.io/parcours_r_exercices/index.html

**Comment by MaelTheuliere** [comment]
On propose un vote sur une short liste pour les noms : exRcices, savoir_fR, tutR, pratiquR ? avec R majuscule un miniscule ? Pour info, normalement la convention veut qu'on ne mettre que des minuscules dans le nom d'un package mais si on vise pas le cran c'est pas grave...

**Comment by MurielleDelmotte** [comment]
Ok pour la short list.
Comme tu dis, il est plus habituel de mettre que des minuscules (je suis la 1ere à pester quand je me trompe sur un nom à cause de la casse) mais je trouve malgré tout que le R majuscule est plus approprié.

**Comment by TerseurBr** [comment]
> Ok pour la short list.
> Comme tu dis, il est plus habituel de mettre que des minuscules (je suis la 1ere à pester quand je me trompe sur un nom à cause de la casse) mais je trouve malgré tout que le R majuscule est plus approprié.

je suis du meme avis, le cas de la majuscule sur R est a part et se justifiea mon avis

ok pour la shortlist, avec une préférence sur ces pour savoir_fR (ou savoirfR si on veut simplifier et eviter la proximité d'une  maj et d'un caractere special)
