### ISSUE TITLE
Trouver un logo pour le package

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/savoirfR#16]
Parce qu'on ne peut pas sortir un package sans hexsticker

**Comment by MaelTheuliere** [comment]
genre ça ? C'est moche mais bon...
![hex-savoirfR(1)](https://user-images.githubusercontent.com/2116892/82346779-2f6f0c00-99f7-11ea-83f6-cd9f3f71bb36.png)

**Comment by jengelaere** [comment]
![hex-savoirfR](https://user-images.githubusercontent.com/37416795/82348666-7c53e200-99f9-11ea-91fb-2b237aa8837a.png)
![hex-savoirfR2](https://user-images.githubusercontent.com/37416795/82348675-7eb63c00-99f9-11ea-9e33-a6467f5ccf44.png)

**Comment by jengelaere** [comment]
moi aussi j'ai fait joujou !
https://connect.thinkr.fr/hexmake/

**Comment by MZellou** [comment]
Wouah trop beau ! J'aime beaucoup le bleu avec le calepin

**Comment by MaelTheuliere** [comment]
Pareil j'adore le dernier

**Comment by TerseurBr** [comment]
![hex-savoirfR](https://user-images.githubusercontent.com/36697014/82375697-44609500-9a21-11ea-898e-37f18c3eb70c.png)



trop fort le site+package hexmake !

du coup l'envie était trop forte d'en essayer un  

c'est perfectible pcq je n'ai pas pris le temps de detourer l'image (d'ou le fond passé au blanc)

**Comment by jdlom** [comment]
Je me permets de voter aussi. J'aime aussi le bleu. @MurielleL un avis ?

**Comment by MurielleDelmotte** [comment]
J'ai répondu sur Ariane avant de voir ce fil! ce qui est bien c'est qu'on est tous d'accord! le bleu: simple et efficace!

**Comment by jengelaere** [comment]
coucou oui, sur Ariane il y a plus de votants @jdlom
