### ISSUE TITLE
library  à charger sur M5

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/savoirfR#23]
exo4

- forcats  

exo 6
- tidyr
- stringr

J'ai pas osé écrire sur la branche sur laquelle tu travaillais

**Comment by jengelaere** [comment]
C'est corrigé, merci Jean-Dominique !

**Comment by jdlom** [comment]
Tu m'as tué avec ton Jean-Dominique  Je suis sûr que c'est à cause de mon pseudo. :)

**Comment by jengelaere** [comment]
Quelle honte ! milles excuses
c'est vrai que je suis un peu dyslexique et que je lis ton pseudo jldom, mais ça n'excuse pas...
