### ISSUE TITLE
Manque de metadonnée dans le Parcours Socle R (1)

### ISSUE THREAD

**Issue by MarlyseCLEMENT** [MTES-MCT/savoirfR#27]
Bonjour,

Dans le parcours socle les donnes sont disponible dans savoirfR 
Dans le 5.8 sont evoqué les metadonnée pour comprendre quelle varaibles utilisée par la suite ....
" Le fichier source (Excel) figure dans le sous-répertoire “data” et contient toutes les métadonnées."

Or dans savoirfR les metadonnées ne sont pas présentes.... 
Merci à Murielle elles sont explicitées dans une autres des formations.

Avec calc je les ai donc mis en forme sous ODS. Je joints donc le fichier à rajouter dans savoirfR. 

Merci d'avance pour les suivants ! :)
[metabase.ods](https://github.com/MTES-MCT/savoirfR/files/7793467/metabase.ods)

**Comment by jengelaere** [comment]
En effet, j'ai intégrée les métadonnées au support du M1 et on va aussi ajouter dans savoirFr. merci @MarlyseCLEMENT
