### ISSUE TITLE
Erreur extract_r_files

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/savoirfR#32]
@jengelaere j'ai une erreur quand j'execute la fonction, et c'est lié à gsub

```
library(savoirfR)
extract_r_files(module = 5)
```
Est-ce que tu reproduis ?

```

processing file: inst/vignettes/m5/exo1.rmd
  |.....................................................................| 100%
output file: inst/rstudio/templates/project/ressources/m5/corrections/exo1.R

Error in `mutate_cols()`:
! Problem with `mutate()` column `value`.
ℹ `value = ... %>% ...`.
x zero-length pattern
Caused by error in `gsub()`:
! zero-length pattern
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Problem with `mutate()` column `value`.
ℹ `value = ... %>% ...`.
ℹ argument 'pattern' has length > 1 and only the first element will be used 
```

**Comment by jengelaere** [comment]
coucou @jdlom a priori non, j'avais recréé tous les exos pour vérifier que ça marchait, je vérifie et te tiens au courant

**Comment by jengelaere** [comment]
je reproduis, c'est le ` .` transformé en `.data` à la va vite après les checks qui n'est pas bon 😕

**Comment by jengelaere** [comment]
```
clean_r: no visible binding for global variable '.'
   Undefined global functions or variables:
```

**Comment by jdlom** [comment]
Tu peux assigner dans la fonction
` . <- NULL` pour supprimer cette alerte

J'ai déjà vu Colin Fay faire cela

**Comment by jengelaere** [comment]
C'est pas bien de dénoncer !! 😄 
Je t'ai proposé une PR avec une solution pas très élégante qui marche aussi, n'hésite pas à remplacer si tu préfères la solution de Colin
