### ISSUE TITLE
Module 5 exo 6 : Problème de lien relatif d'image .gif généré par gganimate

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/savoirfR#34]
Poke @jengelaere 

Il y a un problème sur le rendu de l'exercice de l'exercice 6 du module 5
Pour le moment le code ne s’exécute pas mais c'est parce qu'il manque `forcats`.

La vignette compile bien après intégration de `forcats` (je pense que cela passera dans les bookdown et que l'image sera bien intégrée). En revanche,
cela ne fonctionne pas avec `pkgdown`. J'ai épluché les issues du package, et le problème provient du fait que le chemin n'est pas en relatif mais en absolu.
J'ai un fix pas beau mais qui fonctionne.

https://mtes-mct.github.io/savoirfR/articles/exercices_module_datavisualisation_R.html

**Comment by jengelaere** [comment]
coucou @jdlom tu pousses ton fix pas beau qui fonctionne ? si besoin on peut tricher et afficher directement l'image au lieu de rendre le résultat de la correction

**Comment by jengelaere** [comment]
A priori ça vient d'un bug dans https://github.com/r-lib/pkgdown/issues/2334

**Comment by jengelaere** [comment]
@jdlom coucou JD, as-tu une idée de pourquoi au lieu d'avoir un lien cassé on a une sortie à NULL au niveau du résultat attendu ?
J'arrive pas à reproduire chez moi.
