### ISSUE TITLE
impossible d'installer le package

### ISSUE THREAD

**Issue by ChD45** [MTES-MCT/savoirfR#39]
Je ne suis peut-être pas au bon endroit étant( complétement novice mais j'ai le message ci-dessous quand j'essaie d'installer le package savoirfR. Pouvez-vous m'aider ?
> remotes::install_github("MTES-MCT/savoirfR")
Downloading GitHub repo MTES-MCT/savoirfR@HEAD
Error: Failed to install 'savoirfR' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command '"C:\PROGRA~2\Git\cmd\git.exe" ls-remote https://gitlab-forge.din.developpement-durable.gouv.fr/dreal-pdl/csd/mapfactory.git main' had status 128

**Comment by jengelaere** [comment]
Bonjour, c'est difficile à diagnostiquer de l'extérieur,
si l'installation automatique de la dépendance mapfactory ne fonctionne pas il faut peut être la forcer en l'installant préalablement avec 
```
remotes::install_gitlab(repo = "dreal-pdl/csd/mapfactory", 
                        host = "gitlab-forge.din.developpement-durable.gouv.fr")
```
L'erreur peut également être due à une indisponibilité temporaire du serveur qui héberge mapfactory.
