### ISSUE TITLE
Bascule exercices m3

### ISSUE THREAD

**Issue by MaelTheuliere** [MTES-MCT/savoirfR#5]

**Comment by TerseurBr** [comment]
Sir, yes sir !   ;-)

**Comment by TerseurBr** [comment]
Hello @MaelTheuliere 

souci au démarrage

j'ai installé et chargé le package [  library(exercices) ], je veux créer le m3, et j'ai ceci :


Error in system.file(..., package = "exercices", mustWork = TRUE) : 
  no file found


(AH, peut-etre parce que je n'ai pas créé lé branche sur Git au prealable ?
mais ca a l'air d'etre local plutot)

**Comment by MaelTheuliere** [comment]
oui tu dois cloné ce projet via git et travaillé à partir de là pas du package.
